### ISSUE TITLE
popover flashes open and closed when hover over drop pin

### ISSUE THREAD

**Issue by LucianBuzzo** [danbz/signs-of-surveillance-web#2]
When looking at signs in Italy the popover will open and close again repeatedly

https://www.whatsmybrowser.org/b/PVWDY6U

![sign-popover](https://user-images.githubusercontent.com/15064535/56144848-08940a00-5f9b-11e9-927e-8c32ad4c6564.gif)

**Comment by danbz** [comment]
believe this is related to issue #1  as mouseOver and mouseLeave message are repeatedly sent as popup appears and dissapears...

**Comment by danbz** [comment]
closed as per issue #1
